# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C implementation of the bslearn function
#'
#' @param nrows number of rows
#' @param ncols number of columns
#' @param input_y Integer vector 
#' @param input_x Integer matrix
#' @param grp group membership indices
#' @param max_rules max number of rules
#' @param max_time max running time in seconds
#' @param node_size minimum node size
#' @param no_same_gender_children if TRUE child nodes must be of different predicted classes
#' @param verbose verbose level
#' @return a list containing four elements
rcpp_bslearn <- function(nrows, ncols, input_y, input_x, grp, max_rules, max_time, node_size, no_same_gender_children, verbose) {
    .Call(`_bsnsing_rcpp_bslearn`, nrows, ncols, input_y, input_x, grp, max_rules, max_time, node_size, no_same_gender_children, verbose)
}

